apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-deny-all
  namespace: test
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: "true"
    - namespaceSelector:
        matchExpressions:
        - key: namespace
          operator: In
          values:
          - kube-system
          - ingress-nginx
          - monitoring

    ports:
    - protocol: TCP
      port: 80
